### ISSUE TITLE
Creating Scraper

### ISSUE THREAD

**Issue by JanKrupiniewicz** [JanKrupiniewicz/project-prestashop#1]

**Comment by HubGitPL** [comment]
Thank you Jan for providing me this issue. I'll take care of this :). My results will be in csv file and results will include: category, subcategory, name, price, description, photo and maybe more. I will try to keep you updated.

**Comment by HubGitPL** [comment]
Reopened to merge two scripts and include results in json file

**Comment by JanKrupiniewicz** [comment]
![image](https://github.com/user-attachments/assets/1e5fd9d0-f51e-42b2-800e-9a199757eaa7)
![image](https://github.com/user-attachments/assets/6f2b1b3a-c1a4-4ccd-8fed-3e8ec5b1c06a)

**Comment by HubGitPL** [comment]
<img width="380" alt="Screenshot 2024-12-01 at 20 22 13" src="https://github.com/user-attachments/assets/8641e2bd-503d-4282-9946-4311fc7049f8">
<br />4 categories + 2 subcategories in each done. All products in progress

**Comment by HubGitPL** [comment]
Closing the issue as requirements have been met
